spring:
  application:
    name: toy
  security:
    user:
      name: user
      password: 1111
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??

server:
  port: 8081


# 도서 url
book:
  url: https://www.nl.go.kr/NL/search/openApi/search.do
  key: ${BOOK_API_KEY}