spring:
  application:
    name: toy
  security:
    user:
      name: user
      password: 1111
  datasource:
    url: ${spring.datasource.url:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username:}
    password: ${spring.datasource.password:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??

server:
  port: 8081


# 도서 url
book:
  url: https://www.nl.go.kr/NL/search/openApi/search.do
  key: ${book.api.key:}